### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by yamanq**
@eliyazdi @thomasebsmith Your approval is needed

Licensing our software is an important step in becoming a mature organization. I believe that the MIT license is the best option for this project. Please see our [meeting notes](https://docs.google.com/presentation/d/1zK38xOiIaG-YE_WRLEEBhm5gFcFmC1T3E60nswZ1694/edit) for details. If you have any questions, feel free to message me on Slack or leave a comment on this pull request.

**Please comment on this pull request to approve this licensing change**. Otherwise, please comment what license you are willing to use, as currently there are no clear terms.

### CODE REVIEW

**Comment by thomasebsmith** [comment]
I am in favor of this change. However, I think we also need approval from @vuqt06 (Vu Trinh) and @ailijevski (Angelina Ilijevski).

**Comment by yamanq** [comment]
Thanks for letting me know. For some reason GitHub only displayed your name and Eli Yazdi's name on the contributors page.

@vuqt06 @ailijevski I apologize for missing you in the first message, but it also applies to you. Please comment your thoughts on this licensing change.

**Comment by ailijevski** [comment]
I am also in favor of this change. Thank you for letting me know!

**Comment by eliyazdi** [comment]
I am in favor of this change.

**Comment by yamanq** [comment]
@vuqt06 What are your opinions about this licensing change?

**Comment by vuqt06** [comment]
Sorry for the late reply. I am also in favor of this change.

**Comment by yamanq** [comment]
Great, thanks everyone. I'll go ahead and merge this then.

**Pull request merged**
